#%RAML 1.0
title: System SFTP ERP


types:
  Article: !include Project_Types/articleType.raml

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    queryParameters:
      forceAddParams:
        required: false
    responses:
      401:
        description: Unauthorized, The client_id or client_secret are not valid or the client does not have access.

/SFTP:
  is: [client-id-required]
  post:
    description: Add Articles
    
    body:
      application/json:
        type: array
        items: Article
        examples:
          input : !include Project_TypesExemples/articles.json
    responses:
      201:
        body:
          application/json:
            example:
              message : Article Added  
  get:
    
     description: Presence de fichier
     
     responses:
      201:
        body:
          application/json:
            example:
               message : !include Project_TypesExemples/path.json



